server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
  instance:
   prefer-ip-address: true
        
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: hellowold-service
        uri: lb://hellowold-service
        predicates:
        - Path=/hellowold/**
        filters:
        - RewritePath=/hellowold/(?<path>.*), /$\{path}
      
springdoc:
  swagger-ui:
    urls:
      - name: hellowold
        url: /v3/api-docs/hellowold